{-# OPTIONS_GHC -F -pgmF htfpp #-}
module Main where


import Test.Framework

import {-@ HTF_TESTS @-} Problems.Prob1Test
import {-@ HTF_TESTS @-} Problems.Prob2Test
import {-@ HTF_TESTS @-} Problems.Prob3Test
import {-@ HTF_TESTS @-} Problems.Prob4Test
import {-@ HTF_TESTS @-} Problems.Prob5Test
import {-@ HTF_TESTS @-} Problems.Prob6Test
import {-@ HTF_TESTS @-} Problems.Prob7Test
import {-@ HTF_TESTS @-} Problems.Prob8Test
import {-@ HTF_TESTS @-} Problems.Prob9Test
import {-@ HTF_TESTS @-} Problems.Prob10Test
import {-@ HTF_TESTS @-} Problems.Prob11Test
import {-@ HTF_TESTS @-} Problems.Prob12Test
import {-@ HTF_TESTS @-} Problems.Prob13Test
import {-@ HTF_TESTS @-} Problems.Prob14Test
import {-@ HTF_TESTS @-} Problems.Prob15Test
import {-@ HTF_TESTS @-} Problems.Prob16Test
import {-@ HTF_TESTS @-} Problems.Prob17Test
import {-@ HTF_TESTS @-} Problems.Prob18Test
import {-@ HTF_TESTS @-} Problems.Prob19Test
import {-@ HTF_TESTS @-} Problems.Prob20Test
import {-@ HTF_TESTS @-} Problems.Prob21Test
import {-@ HTF_TESTS @-} Problems.Prob22Test
import {-@ HTF_TESTS @-} Problems.Prob23Test
import {-@ HTF_TESTS @-} Problems.Prob24Test
import {-@ HTF_TESTS @-} Problems.Prob25Test
import {-@ HTF_TESTS @-} Problems.Prob26Test
import {-@ HTF_TESTS @-} Problems.Prob27Test
import {-@ HTF_TESTS @-} Problems.Prob28Test
import {-@ HTF_TESTS @-} Problems.Prob29Test
import {-@ HTF_TESTS @-} Problems.Prob30Test
import {-@ HTF_TESTS @-} Problems.Prob31Test
import {-@ HTF_TESTS @-} Problems.Prob32Test
import {-@ HTF_TESTS @-} Problems.Prob33Test
import {-@ HTF_TESTS @-} Problems.Prob34Test
import {-@ HTF_TESTS @-} Problems.Prob35Test
import {-@ HTF_TESTS @-} Problems.Prob36Test
import {-@ HTF_TESTS @-} Problems.Prob37Test
import {-@ HTF_TESTS @-} Problems.Prob38Test
import {-@ HTF_TESTS @-} Problems.Prob39Test
import {-@ HTF_TESTS @-} Problems.Prob40Test
import {-@ HTF_TESTS @-} Problems.Prob41Test
import {-@ HTF_TESTS @-} Problems.Prob42Test
import {-@ HTF_TESTS @-} Problems.Prob43Test
import {-@ HTF_TESTS @-} Problems.Prob44Test
import {-@ HTF_TESTS @-} Problems.Prob45Test
import {-@ HTF_TESTS @-} Problems.Prob46Test
import {-@ HTF_TESTS @-} Problems.Prob47Test
import {-@ HTF_TESTS @-} Problems.Prob48Test
import {-@ HTF_TESTS @-} Problems.Prob49Test
import {-@ HTF_TESTS @-} Problems.Prob50Test
import {-@ HTF_TESTS @-} Problems.Prob51Test
import {-@ HTF_TESTS @-} Problems.Prob52Test
import {-@ HTF_TESTS @-} Problems.Prob53Test
import {-@ HTF_TESTS @-} Problems.Prob54Test
import {-@ HTF_TESTS @-} Problems.Prob55Test
import {-@ HTF_TESTS @-} Problems.Prob56Test
import {-@ HTF_TESTS @-} Problems.Prob57Test
import {-@ HTF_TESTS @-} Problems.Prob58Test
import {-@ HTF_TESTS @-} Problems.Prob59Test
import {-@ HTF_TESTS @-} Problems.Prob60Test
import {-@ HTF_TESTS @-} Problems.Prob61Test
import {-@ HTF_TESTS @-} Problems.Prob62Test
import {-@ HTF_TESTS @-} Problems.Prob63Test
import {-@ HTF_TESTS @-} Problems.Prob64Test
import {-@ HTF_TESTS @-} Problems.Prob65Test
import {-@ HTF_TESTS @-} Problems.Prob66Test
import {-@ HTF_TESTS @-} Problems.Prob67Test
import {-@ HTF_TESTS @-} Problems.Prob68Test
import {-@ HTF_TESTS @-} Problems.Prob69Test
import {-@ HTF_TESTS @-} Problems.Prob70Test
import {-@ HTF_TESTS @-} Problems.Prob71Test
import {-@ HTF_TESTS @-} Problems.Prob72Test
import {-@ HTF_TESTS @-} Problems.Prob73Test
import {-@ HTF_TESTS @-} Problems.Prob74Test
import {-@ HTF_TESTS @-} Problems.Prob75Test
import {-@ HTF_TESTS @-} Problems.Prob76Test
import {-@ HTF_TESTS @-} Problems.Prob77Test
import {-@ HTF_TESTS @-} Problems.Prob78Test
import {-@ HTF_TESTS @-} Problems.Prob79Test
import {-@ HTF_TESTS @-} Problems.Prob80Test
import {-@ HTF_TESTS @-} Problems.Prob81Test
import {-@ HTF_TESTS @-} Problems.Prob82Test
import {-@ HTF_TESTS @-} Problems.Prob83Test
import {-@ HTF_TESTS @-} Problems.Prob84Test
import {-@ HTF_TESTS @-} Problems.Prob85Test
import {-@ HTF_TESTS @-} Problems.Prob86Test
import {-@ HTF_TESTS @-} Problems.Prob87Test
import {-@ HTF_TESTS @-} Problems.Prob88Test
import {-@ HTF_TESTS @-} Problems.Prob89Test
import {-@ HTF_TESTS @-} Problems.Prob90Test
import {-@ HTF_TESTS @-} Problems.Prob91Test
import {-@ HTF_TESTS @-} Problems.Prob92Test
import {-@ HTF_TESTS @-} Problems.Prob93Test
import {-@ HTF_TESTS @-} Problems.Prob94Test
import {-@ HTF_TESTS @-} Problems.Prob95Test
import {-@ HTF_TESTS @-} Problems.Prob96Test
import {-@ HTF_TESTS @-} Problems.Prob97Test
import {-@ HTF_TESTS @-} Problems.Prob98Test
import {-@ HTF_TESTS @-} Problems.Prob99Test
import {-@ HTF_TESTS @-} Problems.Prob100Test
import {-@ HTF_TESTS @-} Problems.Prob101Test
import {-@ HTF_TESTS @-} Problems.Prob102Test
import {-@ HTF_TESTS @-} Problems.Prob103Test
import {-@ HTF_TESTS @-} Problems.Prob104Test
import {-@ HTF_TESTS @-} Problems.Prob108Test
import {-@ HTF_TESTS @-} Problems.Prob110Test
import {-@ HTF_TESTS @-} Problems.Prob112Test
import {-@ HTF_TESTS @-} Problems.Prob121Test
import {-@ HTF_TESTS @-} Problems.Prob122Test
import {-@ HTF_TESTS @-} Problems.Prob144Test
import {-@ HTF_TESTS @-} Problems.Prob145Test
import {-@ HTF_TESTS @-} Problems.Prob169Test
import {-@ HTF_TESTS @-} Problems.Prob233Test
import {-@ HTF_TESTS @-} Problems.Prob243Test

main :: IO()
main = htfMain htf_importedTests
